# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

#inhibit_all_warnings!

target 'CollectionAlignedLayout_Example' do
    use_frameworks!

  pod 'CollectionAlignedLayout', :path => '../'

  target 'CollectionAlignedLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
  
end
